
# pre-commit is a tool to perform a predefined set of tasks manually and/or
# automatically before git commits are made.
#
# Config reference: https://pre-commit.com/#pre-commit-configyaml---top-level
#
# Common tasks
#
# - Run on all files:   pre-commit run --all-files
# - Register git hooks: pre-commit install --install-hooks
#
repos:
  # Autoformat: Python code, syntax patterns are modernized
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus

  # Autoformat: Python code
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  # Autoformat and linting, misc. details
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
        exclude: share/jupyterhub/static/js/admin-react.js
      - id: check-case-conflict

  # Linting: Python code (see the file .flake8)
  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        args:
          # making isort line length compatible with black
          - "--max-line-length=88"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"

          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=E203,E266,E501,W503,F403,F401,E402"
